/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurante;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio
 */
public class Restaurante extends javax.swing.JFrame {

    /**
     * Creates new form Restaurante
     */
    public Restaurante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumMesa = new javax.swing.JLabel();
        jLabelNumBarra = new javax.swing.JLabel();
        jLabelNumRestaurante = new javax.swing.JLabel();
        jLabelMesa1 = new javax.swing.JLabel();
        jLabelMesa2 = new javax.swing.JLabel();
        jLabelMesa3 = new javax.swing.JLabel();
        jLabelMesa4 = new javax.swing.JLabel();
        jLabelMesa5 = new javax.swing.JLabel();
        jLabelMesa6 = new javax.swing.JLabel();
        jLabelMesa7 = new javax.swing.JLabel();
        jLabelMesa8 = new javax.swing.JLabel();
        jLabelMesa9 = new javax.swing.JLabel();
        jLabelMesa10 = new javax.swing.JLabel();
        jLabelMesa11 = new javax.swing.JLabel();
        jLabelMesa12 = new javax.swing.JLabel();
        jComboBoxCap1 = new javax.swing.JComboBox<>();
        jComboBoxCap2 = new javax.swing.JComboBox<>();
        jComboBoxCap3 = new javax.swing.JComboBox<>();
        jComboBoxCap4 = new javax.swing.JComboBox<>();
        jComboBoxCap5 = new javax.swing.JComboBox<>();
        jComboBoxCap6 = new javax.swing.JComboBox<>();
        jComboBoxCap7 = new javax.swing.JComboBox<>();
        jComboBoxCap8 = new javax.swing.JComboBox<>();
        jComboBoxCap9 = new javax.swing.JComboBox<>();
        jComboBoxCap10 = new javax.swing.JComboBox<>();
        jComboBoxCap11 = new javax.swing.JComboBox<>();
        jComboBoxCap12 = new javax.swing.JComboBox<>();
        jLabelBarra = new javax.swing.JLabel();
        jComboBoxCapBarra = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNumMesa.setText("En mesas: 0 / 54");

        jLabelNumBarra.setText("En barra: 0 / 12");

        jLabelNumRestaurante.setText("Total en restaurante: 0 / 60");

        jLabelMesa1.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa1.setText("Mesa 1");
        jLabelMesa1.setOpaque(true);

        jLabelMesa2.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa2.setText("Mesa 2");
        jLabelMesa2.setOpaque(true);

        jLabelMesa3.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa3.setText("Mesa 3");
        jLabelMesa3.setOpaque(true);

        jLabelMesa4.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa4.setText("Mesa 4");
        jLabelMesa4.setOpaque(true);

        jLabelMesa5.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa5.setText("Mesa 5");
        jLabelMesa5.setOpaque(true);

        jLabelMesa6.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa6.setText("Mesa 6");
        jLabelMesa6.setOpaque(true);

        jLabelMesa7.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa7.setText("Mesa 7");
        jLabelMesa7.setOpaque(true);

        jLabelMesa8.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa8.setText("Mesa 8");
        jLabelMesa8.setOpaque(true);

        jLabelMesa9.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa9.setText("Mesa 9");
        jLabelMesa9.setOpaque(true);

        jLabelMesa10.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa10.setText("Mesa 10");
        jLabelMesa10.setOpaque(true);

        jLabelMesa11.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa11.setText("Mesa 11");
        jLabelMesa11.setOpaque(true);

        jLabelMesa12.setBackground(new java.awt.Color(0, 255, 0));
        jLabelMesa12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa12.setText("Mesa 12");
        jLabelMesa12.setOpaque(true);

        jComboBoxCap1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap1ActionPerformed(evt);
            }
        });

        jComboBoxCap2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap2ActionPerformed(evt);
            }
        });

        jComboBoxCap3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap3ActionPerformed(evt);
            }
        });

        jComboBoxCap4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap4ActionPerformed(evt);
            }
        });

        jComboBoxCap5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCap5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap5ActionPerformed(evt);
            }
        });

        jComboBoxCap6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCap6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap6ActionPerformed(evt);
            }
        });

        jComboBoxCap7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));
        jComboBoxCap7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap7ActionPerformed(evt);
            }
        });

        jComboBoxCap8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));
        jComboBoxCap8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap8ActionPerformed(evt);
            }
        });

        jComboBoxCap9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCap9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap9ActionPerformed(evt);
            }
        });

        jComboBoxCap10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCap10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap10ActionPerformed(evt);
            }
        });

        jComboBoxCap11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCap11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap11ActionPerformed(evt);
            }
        });

        jComboBoxCap12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCap12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCap12ActionPerformed(evt);
            }
        });

        jLabelBarra.setBackground(new java.awt.Color(0, 255, 0));
        jLabelBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBarra.setText("Barra");
        jLabelBarra.setOpaque(true);

        jComboBoxCapBarra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBoxCapBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapBarraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNumRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNumBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNumMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelMesa6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxCap6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBoxCap5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxCap1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxCap2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCap4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMesa3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCap3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxCap8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCap7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMesa9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCap10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCap9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jLabelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMesa12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCap12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jComboBoxCap11, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMesa11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jComboBoxCapBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNumMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNumBarra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNumRestaurante)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxCap10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCap12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxCap8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCap7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCap11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCap9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCap5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCap4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCap6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMesa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMesa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCap3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jLabelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCapBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int[] capacidadMesas = {4, 4, 4, 4, 4, 4, 2, 2, 8, 8, 8, 8};
    int[] ocupacionMesas = new int[12];
    int personasBarra = 0;

    final int maxSentados = 54;
    final int maxTotal = 60;
    final int maxBarra = 12;
    
    private JLabel obtenerLabelMesa(int numeroMesa) {
        switch (numeroMesa) {
            case 1: return jLabelMesa1;
            case 2: return jLabelMesa2;
            case 3: return jLabelMesa3;
            case 4: return jLabelMesa4;
            case 5: return jLabelMesa5;
            case 6: return jLabelMesa6;
            case 7: return jLabelMesa7;
            case 8: return jLabelMesa8;
            case 9: return jLabelMesa9;
            case 10: return jLabelMesa10;
            case 11: return jLabelMesa11;
            case 12: return jLabelMesa12;
            default: return null;
        }
    }
    
    private void actualizarContadores() {
        int totalMesas = 0;
        int mesasLibres = 0;
        int mesasOcupadas = 0;

        for (int i = 0; i < ocupacionMesas.length; i++) {
            totalMesas += ocupacionMesas[i];
            if (ocupacionMesas[i] == 0) {
                mesasLibres++;
            } else {
                mesasOcupadas++;
            }
        }

        int totalRestaurante = totalMesas + personasBarra;

        jLabelNumMesa.setText("En mesas: " + totalMesas + " / " + maxSentados);
        jLabelNumBarra.setText("En barra: " + personasBarra + " / " + maxBarra);
        jLabelNumRestaurante.setText("Total en restaurante: " + totalRestaurante + " / " + maxTotal);

        for (int i = 0; i < ocupacionMesas.length; i++) {
            int ocup = ocupacionMesas[i];
            JLabel etiqueta = obtenerLabelMesa(i + 1);
            if (ocup == 0) {
                etiqueta.setBackground(Color.green);
            } else if (ocup == capacidadMesas[i]) {
                etiqueta.setBackground(Color.red);
            } else {
                etiqueta.setBackground(Color.yellow);
            }
            etiqueta.setOpaque(true);
        }
    }
    
    private int calcularSentadosSinMesa(int numeroMesa) {
        int total = 0;
        for (int i = 0; i < ocupacionMesas.length; i++) {
            if (i != (numeroMesa - 1)) total += ocupacionMesas[i];
        }
        return total;
    }
    
    private void jComboBoxCap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap1ActionPerformed
        int valorAnterior = ocupacionMesas[0];
        int nuevoValor = Integer.parseInt(jComboBoxCap1.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(1);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap1.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap1.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[0] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap1ActionPerformed

    private void jComboBoxCap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap2ActionPerformed
        int valorAnterior = ocupacionMesas[1];
        int nuevoValor = Integer.parseInt(jComboBoxCap2.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(2);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap2.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap2.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[1] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap2ActionPerformed

    private void jComboBoxCap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap3ActionPerformed
        int valorAnterior = ocupacionMesas[2];
        int nuevoValor = Integer.parseInt(jComboBoxCap3.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(3);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap3.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap3.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[2] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap3ActionPerformed

    private void jComboBoxCap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap4ActionPerformed
        int valorAnterior = ocupacionMesas[3];
        int nuevoValor = Integer.parseInt(jComboBoxCap4.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(4);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap4.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap4.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[3] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap4ActionPerformed

    private void jComboBoxCap5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap5ActionPerformed
        int valorAnterior = ocupacionMesas[4];
        int nuevoValor = Integer.parseInt(jComboBoxCap5.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(5);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap5.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap5.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[4] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap5ActionPerformed

    private void jComboBoxCap6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap6ActionPerformed
        int valorAnterior = ocupacionMesas[5];
        int nuevoValor = Integer.parseInt(jComboBoxCap6.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(6);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap6.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap6.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[5] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap6ActionPerformed

    private void jComboBoxCap7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap7ActionPerformed
        int valorAnterior = ocupacionMesas[6];
        int nuevoValor = Integer.parseInt(jComboBoxCap7.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(7);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap7.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap7.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[6] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap7ActionPerformed

    private void jComboBoxCap8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap8ActionPerformed
        int valorAnterior = ocupacionMesas[7];
        int nuevoValor = Integer.parseInt(jComboBoxCap8.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(8);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap8.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap8.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[7] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap8ActionPerformed

    private void jComboBoxCap9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap9ActionPerformed
        int valorAnterior = ocupacionMesas[8];
        int nuevoValor = Integer.parseInt(jComboBoxCap9.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(9);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap9.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap9.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[8] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap9ActionPerformed

    private void jComboBoxCap10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap10ActionPerformed
        int valorAnterior = ocupacionMesas[9];
        int nuevoValor = Integer.parseInt(jComboBoxCap10.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(10);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap10.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap10.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[9] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap10ActionPerformed

    private void jComboBoxCap11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap11ActionPerformed
        int valorAnterior = ocupacionMesas[10];
        int nuevoValor = Integer.parseInt(jComboBoxCap11.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(11);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap11.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap11.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[10] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap11ActionPerformed

    private void jComboBoxCap12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCap12ActionPerformed
        int valorAnterior = ocupacionMesas[11];
        int nuevoValor = Integer.parseInt(jComboBoxCap12.getSelectedItem().toString());
        int totalAntes = calcularSentadosSinMesa(12);
        if (totalAntes + nuevoValor > maxSentados) {
            JOptionPane.showMessageDialog(this, "No se puede superar la capacidad sentada de " + maxSentados);
            jComboBoxCap12.setSelectedIndex(valorAnterior);
            return;
        }
        if (totalAntes + nuevoValor + personasBarra > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCap12.setSelectedIndex(valorAnterior);
            return;
        }
        ocupacionMesas[11] = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCap12ActionPerformed

    private void jComboBoxCapBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapBarraActionPerformed
        int valorAnterior = personasBarra;
        int nuevoValor = Integer.parseInt(jComboBoxCapBarra.getSelectedItem().toString());
        int sentados = 0;
        if (jComboBoxCapBarra.getSelectedItem().toString() == "12") {
            jLabelBarra.setBackground(Color.red);
        } else if (jComboBoxCapBarra.getSelectedItem().toString() == "0") {
            jLabelBarra.setBackground(Color.green);
        } else {
            jLabelBarra.setBackground(Color.yellow);
        }
        
        for (int o : ocupacionMesas) sentados += o;
        if (sentados + nuevoValor > maxTotal) {
            JOptionPane.showMessageDialog(this, "Capacidad total (mesas + barra) excedida");
            jComboBoxCapBarra.setSelectedIndex(valorAnterior);
            return;
        }
        personasBarra = nuevoValor;
        actualizarContadores();
    }//GEN-LAST:event_jComboBoxCapBarraActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCap1;
    private javax.swing.JComboBox<String> jComboBoxCap10;
    private javax.swing.JComboBox<String> jComboBoxCap11;
    private javax.swing.JComboBox<String> jComboBoxCap12;
    private javax.swing.JComboBox<String> jComboBoxCap2;
    private javax.swing.JComboBox<String> jComboBoxCap3;
    private javax.swing.JComboBox<String> jComboBoxCap4;
    private javax.swing.JComboBox<String> jComboBoxCap5;
    private javax.swing.JComboBox<String> jComboBoxCap6;
    private javax.swing.JComboBox<String> jComboBoxCap7;
    private javax.swing.JComboBox<String> jComboBoxCap8;
    private javax.swing.JComboBox<String> jComboBoxCap9;
    private javax.swing.JComboBox<String> jComboBoxCapBarra;
    private javax.swing.JLabel jLabelBarra;
    private javax.swing.JLabel jLabelMesa1;
    private javax.swing.JLabel jLabelMesa10;
    private javax.swing.JLabel jLabelMesa11;
    private javax.swing.JLabel jLabelMesa12;
    private javax.swing.JLabel jLabelMesa2;
    private javax.swing.JLabel jLabelMesa3;
    private javax.swing.JLabel jLabelMesa4;
    private javax.swing.JLabel jLabelMesa5;
    private javax.swing.JLabel jLabelMesa6;
    private javax.swing.JLabel jLabelMesa7;
    private javax.swing.JLabel jLabelMesa8;
    private javax.swing.JLabel jLabelMesa9;
    private javax.swing.JLabel jLabelNumBarra;
    private javax.swing.JLabel jLabelNumMesa;
    private javax.swing.JLabel jLabelNumRestaurante;
    // End of variables declaration//GEN-END:variables
}